version: 0.2
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS
  pre_build:
    commands:
      - echo Restore started on `date`
 
      - dotnet restore ./NumberToWordsProject.sln
 
      - dotnet restore ./src/NumberToWords.API/NumberToWords.API.csproj
     
  build:
    commands:
      - echo Build started on `date`
 
      - dotnet build ./NumberToWordsProject.sln
 
      - dotnet build ./src/NumberToWords.API/NumberToWords.API.csproj
     
  post_build:
    commands:
      - echo Build completed on `date`
 
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/NumberToWords.API/NumberToWords.API.csproj --self-contained false
 
artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no
reports:  
    NumberToWordsProject:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'